FROM node:20-alpine AS build-frontend
WORKDIR /app/client
COPY ./client/package*.json ./
RUN npm install
COPY ./client ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY ./server/package*.json ./
RUN npm install
COPY ./server ./

# copy frontend build into server image
COPY --from=build-frontend /app/client/dist ./client/dist

EXPOSE 5001
CMD ["npm", "start"]
